CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL
);

CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_no VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    policy_type VARCHAR(30) NOT NULL,
    base_premium INT NOT NULL,
    status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_policy_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
);

CREATE TABLE claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_no VARCHAR(30) NOT NULL UNIQUE,
    policy_id BIGINT NOT NULL,
    claim_amount INT NOT NULL,
    urgency VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_claim_policy
        FOREIGN KEY (policy_id)
        REFERENCES policies(id)
);

CREATE TABLE riders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE policy_riders (
    policy_id BIGINT NOT NULL,
    rider_id BIGINT NOT NULL,

    PRIMARY KEY (policy_id, rider_id),

    CONSTRAINT fk_policy_rider_policy
        FOREIGN KEY (policy_id)
        REFERENCES policies(id),

    CONSTRAINT fk_policy_rider_rider
        FOREIGN KEY (rider_id)
        REFERENCES riders(id)
);